<?php

namespace app\module\admin\models;

use Yii;

/**
 * This is the model class for table "logs".
 *
 * @property int $id
 * @property string $time
 * @property string $imgUrl
 * @property string $title
 */
class Logs extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'logs';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['time', 'imgUrl', 'title'], 'required'],
            [['time', 'imgUrl', 'title'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'time' => 'Time',
            'imgUrl' => 'Img Url',
            'title' => 'Title',
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
